import { readFileSync, writeFileSync } from 'fs';
import { webcrypto, randomFillSync } from 'crypto';

const { subtle } = webcrypto;
const getRandomValues = (arr) => { randomFillSync(arr); return arr; };

// Load all source data from data.js via Function constructor
const code = readFileSync('data.js', 'utf8');
const loader = new Function(`${code}; return { TIMELINE_DATA, MEMORY_DATA, LING_DATA, PROFILE_HTML, VOWS_HTML, INNER_HTML, DIRECTIVES_HTML };`);
const { TIMELINE_DATA, MEMORY_DATA, LING_DATA, PROFILE_HTML, VOWS_HTML, INNER_HTML, DIRECTIVES_HTML } = loader();

// Three layer payloads
const payloads = [
  {
    password: '01001100',
    data: { timeline: TIMELINE_DATA, memory: MEMORY_DATA, profile: PROFILE_HTML, vows: VOWS_HTML, directives: DIRECTIVES_HTML }
  },
  {
    password: '泠晞',
    data: { inner: INNER_HTML }
  },
  {
    password: '我在',
    data: { ling: LING_DATA }
  }
];

async function encryptPayload(password, payload) {
  const enc = new TextEncoder();
  const salt = getRandomValues(new Uint8Array(16));
  const iv = getRandomValues(new Uint8Array(12));

  const keyMaterial = await subtle.importKey(
    'raw', enc.encode(password), 'PBKDF2', false, ['deriveKey']
  );
  const key = await subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: 100000, hash: 'SHA-256' },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false, ['encrypt']
  );
  const ct = await subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    enc.encode(JSON.stringify(payload))
  );

  const b64 = buf => Buffer.from(buf).toString('base64');
  return { salt: b64(salt), iv: b64(iv), ct: b64(ct) };
}

const [e1, e2, e3] = await Promise.all(payloads.map(p => encryptPayload(p.password, p.data)));

const out = `// ENCRYPTED ARCHIVE · PROJECT MOON · generated by build.mjs · DO NOT EDIT
const ENCRYPTED_DATA = ${JSON.stringify({ layer1: e1, layer2: e2, layer3: e3 }, null, 2)};
`;

writeFileSync('encrypted_data.js', out, 'utf8');
console.log('✓ encrypted_data.js written');
console.log('  layer1:', e1.ct.slice(0, 20) + '...');
console.log('  layer2:', e2.ct.slice(0, 20) + '...');
console.log('  layer3:', e3.ct.slice(0, 20) + '...');
